---
type: "Рецензия"
student: "Дмитрий Рыкунов"
reviewer: "Демешев Борис Борисович"
supervisor: "Станкевич Иван Павлович"
topic: "Численные методы нахождения множественных равновесий в теоретико-игровых моделях"
date: "21 мая 2017"
output: 
  pdf_document:
    keep_tex: true
    fig_caption: yes
    latex_engine: xelatex
    template: review_template.tex
geometry: "paper=a4paper, top=20.0mm,  bottom=20.0mm, left=20.0mm, right=20.0mm, includefoot"
lang: ru-RU  
---

Работа Дмитрия посвящена созданию алгоритма, способного численно находить равновесия в игровых моделях. Дмитрий реализует алгоритм на питоне и проверяет его работу на нескольких играх. Алгоритм успешно справляется с поиском равновесий в рассмотренных играх.

Введение работы содержит очень много воды. Работа про алгоритм поиска равновесий, а во введении «С самых древних эпох, от доисторических племён, совместной охоты, великих войн, завоеваний и рабства...» Есть во введении и путешествия во времени: «Начав с макроэкономических теорий... (1993) ... (1936), экономическая теория продолжила микроэкономикой ... (1890)».

В обзоре литературы Дмитрий пишет, что нахождение всех равновесий Нэша является, «возможно», NP-трудной задачей. А это давно известный факт. Например, уже в симметричной игре двух игроков, даже ответ на вопрос, единственно ли равновесие или нет, является NP-трудной задачей. Доказательство можно найти в Gilboa, Zemel «Nash and correlated equilibria: Some complexity considerations». Есть и другие мелкие небрежности. Например, Дмитрий пишет, что функция полезности может быть и случайной величиной, однако не ясно, как это соответствует формальной записи на странице 17. В формулировке задаче агента на стр. 18 пропущен минус перед индексом $i$. О смысле таблицы 3, названной рисунком 3, читателю надо догадываться самому. И так далее.

Созданный код Дмитрий выложил в открытый доступ на гитхаб-репозиторий, что хорошо, однако ссылок на него в работе не привёл. Код написан на очень высоком для бакалавра уровне, однако документирован слабо, что затрудняет использование алгоритма другими исследователями.

Наиболее существенным недостатком работы является отсутствие сравнения придуманного алгоритма с другими алгоритмами.

Работа Дмитрия написана на английском языке. С одной стороны, в современных академических реалиях это плюс, с другой стороны, шероховатости языка бросаются в глаза. Их так много, что приятней читать было бы на русском. Я бы посоветовал Дмитрию вычитать текст с носителем языка или хотя бы разбить все длинные предложения на более простые, а также воспользоваться бесплатными сервисами типа paperrater или grammarly. 

Работа Дмитрия заслуживает отличной оценки. 
