---
type: "Рецензия"
student: "Жуйков Дмитрий Игоревич"
reviewer: "Демешев Борис Борисович"
supervisor: "Малаховская Оксана Анатольевна"
topic: "Макроэкономическое прогнозирование с использованием данных различной частотности"
date: "21 мая 2017"
output: 
  pdf_document:
    keep_tex: true
    fig_caption: yes
    latex_engine: xelatex
    template: review_template.tex
geometry: "paper=a4paper, top=20.0mm,  bottom=20.0mm, left=20.0mm, right=20.0mm, includefoot"
lang: ru-RU  
---

В своей работе Дмитрий сравнивает прогнозную силу MIDAS и двумерных VAR моделей для российского ВВП в краткосрочном периоде. 

Дмитрий разобрался с литературой по MIDAS моделям и проводит аналогичные построения на российских данных. Ясно виден большой объём проделанной Дмитрием работы. Есть чётко сформулированные ценные результаты: выявлено преимущество VAR моделей для прогнозирования будущих значений ВВП и небольшое преимущество MIDAS моделей для прогнозирования текущих значений ВВП (nowcasting). Для оценивания моделей Дмитрий использовал статистический пакет R.

О недостатках. Местами работу можно сократить. Фразы типа «применены как общенаучные, так и специфические методы экономической науки» не несут читателю никакой информации.  Модель MIDAS на странице 17 Дмитрий описывает небрежно. Двойной индекс $k$ в формуле, отсутствие описания смысла величины $T_m^x$.

Процедура сезонной корректировки описана поверхностно. Все ли ряды корректировались? С какими параметрами запускалась процедура X13-ARIMA? Графики рядов на рисунках 1-5 — это прогнозы скорректированные на сезонность? Или сделано преобразование прогнозов с очищенной сезонностью обратно к исходным данным? Кстати, названия рисунков неудачные. Например, рисунок 1 называется "Инфляция". Что на нём изображено? Правильно, на нём изображён темп роста ВВП.

В работе не хватает грамотного графического представления результатов. Во-первых, можно попытаться изображать не сами ряды и прогнозы, а ошибки прогнозов. Во-вторых, в дополнение к таблицам отношений RMSE можно добавить сгруппированные по моделям и горизонтам оценённые плотности ошибок прогнозов. В третьих, не хватает графического представления исходных рядов до периода оценивания.

Настоятельно советую Дмитрию выложить код работы с комментариями в открытый доступ, для воспроизводимости результатов.

Работа Дмитрия заслуживает отличной оценки. 
