---
type: "Рецензия"
student: "Волкова Евгения Игоревна"
reviewer: "Демешев Борис Борисович"
supervisor: "Малаховская Оксана Анатольевна"
topic: "Влияние шоков цены на нефть на ключевые макропеременные в SVAR: идентификация с помощью гетерскедастичности"
date: "21 мая 2017"
output: 
  pdf_document:
    keep_tex: true
    fig_caption: yes
    latex_engine: xelatex
    template: review_template.tex
geometry: "paper=a4paper, top=20.0mm,  bottom=20.0mm, left=20.0mm, right=20.0mm, includefoot"
lang: ru-RU  
---

Работа Евгении посвящена оценке силы шоков цены на нефть на макроиндикаторы. Оценку Евгения проводит в рамках модели векторной авторегрессии с переключающимися режимами.

Евгения разобралась в сложных современных моделях и методах оценивания. В классическую векторную авторегрессию добавлена марковская составляющая с переключающимися состояниями, а оценивание производится с помощью алгоритма максимизации ожидания (EM-алгоритм). 

Евгения верно адаптировала и применила к своим целям существующий матлабовский код. Для построения графиков и манипуляций с данными используется среда R. Пожалуй, это самая сложная из десятка прочитанных мной в этом году ВКР.

Мне очень понравилось, что Евгения не вводит идентификационные ограничения «с потолка», а использует модель, в которой ограничения определяются статистическими свойствами имеющихся данных. 

В работе не изучается чувствительность и специфичность используемого метода обнаружения режимов. Было бы интересно посмотреть, например, как часто модель ложно срабатывает и ловит множество режимов на искусственных данных с одним режимом. Было бы также интересно проверить, насколько хорошо отбор модели по AIC совпадает с отбором модели по прогнозной силе вне обучающей выборки.

Хотя я скептически отношусь к осмысленности оценки влияния и интерпретации ненаблюдаемых шоков на наблюдаемые величины, должен отметить, что данная работа выполнена Евгенией добросовестно, в соответствии с принятой в литературе традицией. 

Евгения посвящает часть работы тестированию гипотез о равенстве элементов матрицы $\Lambda_m$. К этому тесту у меня две претензии. Во-первых, он не нужен. Неужели автор верит, что у величин с разными единицами измерения будет абсолютно одинаковая дисперсия? Во-вторых, в работе возникает классическая проблема множественных сравнений и критические значения уже не совпадают с критическими значениями при проведении одного теста.

Есть в работе и мелкие небрежности. Например, в формулировке модели $VAR(p)$ на 11-ой странице не указано последнее слагаемое в формуле, а вектор констант $v$ зависит от $t$. В определении приведённой формы звучит странная фраза «В модели $VAR(p)$ отсутствует взаимосвязь между переменными в момент времени $t$». При всём уважении к правительству слово «правительство» пишется с маленькой буквы. Описание дикого бутстрэпа поверхностное. Формулы незанумерованы. На некоторых графиках не указаны единицы измерения. Не цитированы используемые пакеты R.

Работа красиво оформлена. Очень приятно выглядят графики!

Работа Евгении заслуживает отличной оценки. 
