---
type: "Отзыв"
student: "Звонка Георгий Дмитриевич"
reviewer: "Демешев Борис Борисович"
supervisor: "Демешев Борис Борисович"
topic: "Сбор и анализ данных с российских анонимных торговых площадок"
date: "15 мая 2017"
output: 
  pdf_document:
    keep_tex: true
    fig_caption: yes
    latex_engine: xelatex
    template: review_template.tex
geometry: "paper=a4paper, top=20.0mm,  bottom=20.0mm, left=20.0mm, right=20.0mm, includefoot"
lang: ru-RU  
---

Работа Геогрия посвящена сбору и статистическому анализу данных интернет-торговли наркотиками. Георгий рассматривает две лидирующие по объёму сделок площадки — RAMP и HYDRA.

В работе Георгию удалось:

1. Разработать и успешно реализовать методологию анонимного сбора информации по количеству сделок и их медианной цене.

2. Впервые получить объективные количественные оценки объёма интернет-торговли наркотиками по городам России. И это не экспертные оценки, а результаты обработки данных реальных сделок!

3. Построить индекс торговой активности анонимных площадок.

4. Проверить гипотезу о влиянии курса биткойна на индекс торговой активности.

При выполнении работы Георгию пришлось столкнуться со множеством сложностей. Достаточно отметить, что составление одного слепка состояния всех площадок занимает порядка 10 часов. И эти гигабайтные слепки нужно связывать между собой.

В силу технических сложностей парсинга торговых площадок сети TOR полученный временной ряд довольно короткий и содержит отдельные пропуски. Георгий разобрался с фильтром Калмана и успешно использовал его для заполнения пропусков в данных. К сожалению, никакие статистические методы не могут удлиннить имеющийся ряд данных.

Работать Георгий начал интенсивно ещё до Нового года. Для своих задач успешно освоил и парсинг html-страниц с помощью python, и статистический анализ в R.

Работу нельзя назвать идеально оформленной, а изложение местами затянуто.

Было бы очень интересно продолжить получение ряда данных для проведения более содержательного анализа, благо разработанная методология позволяет это сделать без существенных затрат труда.

Работа Георгия заслуживает отличной оценки. 
