---
type: "Рецензия"
student: "Эркенов Али Ахматович"
reviewer: "Демешев Борис Борисович"
supervisor: "Малаховская Оксана Анатольевна"
topic: "Прогнозирование макроэкономических данных с помощью BVAR"
date: "21 мая 2017"
output: 
  pdf_document:
    keep_tex: true
    fig_caption: yes
    latex_engine: xelatex
    template: review_template.tex
geometry: "paper=a4paper, top=20.0mm,  bottom=20.0mm, left=20.0mm, right=20.0mm, includefoot"
lang: ru-RU  
---

В работе Али исследует прогнозную силу нефтяных цен на темп роста индекс промышленного производства России. Али рассматривает 24 различных спецификации модели, в которые по-разному входят прошлые цены на нефть.

Али получает два неожиданных и интересных результата. Во-первых, при прогнозе на один шаг вперёд модели с нелинейными эффектами без лагов цен на нефть предсказывают лучше, чем с лагами. Во-вторых, модели с годовой нелинейностью по Гамильтону предсказывают лучше, чем с нелинейностью по Морку.

Али пытается содержательно экономически интерпретировать полученные результаты. В векторных авторегрессиях в приведённой форме невозможно содержательно интепретировать коэффициенты модели. А в работе Али в векторную авторегрессию включены нелинейные составляющие, что делает попытки интепретации, на мой взгляд, бессмысленными. 

В работе очень много небрежностей. Незанумерованные страницы и уравнения. Непонятное выражение «знаковая нелинейность между выпуском и нефтяными ценами». Фамилии авторов русских статей логично писать по-русски. В выражении 1 пропущен местами индекс $t$. Проблема одинаково обозначенных параметров присутствует во многих формулах, например, в выражении под выражением 1 приведены совершенно идентичные формулы для выпуска и цены на нефть. Странная фраза «Вместо ВВП в модели используется индекс производительности». В таблице с основными результатами работы указано 9 (девять, Карл!) знаков после запятой и рядом не подписан смысл этих цифр. И так далее.

Основной проблемой работы является отсутствие чёткой спецификации построенных моделей. Али указал, что использует распределение Миннесоты. Однако не сказано, как именно выбираются гиперпараметры, возможно выбраны установки Eviews по-умолчанию. Я не говорю, что это плохой выбор, просто данный выбор нужно описать. 

Кроме того, не указано как именно считается RMSE. Это ошибка при прогнозировании по обучающей выборке или вне обучающей? Если это прогнозы вне обучающей выборки, то как они делались, с помощью скользящей обучающей выборки или с помощью растущей? Если прогнозы делались внутри обучающией выборки, то это резко снижает ценность работы. 

В работе полностью отсутствуют графики. Стиль работы оставляет желать лучшего. Например, можно было структурировать выводы в виде списка и нагляднее объяснить нелинейность по Морку и Гамильтону. 

Работа Али заслуживает удовлетворительной или хорошей оценки. 
