---
type: "Отзыв"
student: "Кузина Анна Вадимовна"
reviewer: "Демешев Борис Борисович"
supervisor: "Демешев Борис Борисович"
topic: "Сравнение прогнозной силы Байесовской векторной авторегрессии с одномерными моделями временных рядов"
date: "15 мая 2017"
output: 
  pdf_document:
    keep_tex: true
    fig_caption: yes
    latex_engine: xelatex
    template: review_template.tex
geometry: "paper=a4paper, top=20.0mm,  bottom=20.0mm, left=20.0mm, right=20.0mm, includefoot"
lang: ru-RU  
---

Работа Анны посвящена сравнению точности различных алгоритмов прогнозирования временных рядов. 

Анна сравнивает современные байесовские векторные модели авторегрессии с меняющимися во времени коэффициентами (TVP-BVAR) и более устоявшиеся модели, оцениваемые методом максимального правдоподобия: ARIMA, экспоненциальное сглаживание и тета-метод.

С одной стороны, модели TVP-BVAR выглядят многообещающими из-за возможности учесть меняющееся взаимодействие между рядами. С другой стороны,  вычислительная сложность TVP-BVAR  резко растёт с ростом количества рядов. Даже десятки рядов могут сделать время вычисления непомерно большим. И пока ещё нет приемлемо быстро работающих процедур автоматического подбора априорных параметров. 

Для решения проблемы использования большого количества рядов в TVP-BVAR модели Анна кластеризует ряды на группы и оценивает TVP-BVAR модели по каждой группе рядов. Для кластеризации Анна использует нелинейным алгоритм t-SNE. Это решение является новым и, вероятно, перспективным при настоящих вычислительных мощностях. Было бы очень интересно построить аналог FAVAR моделей с помощью t-SNE.

Из-за недостатка времени Анна не сравнивает различные априорные распределения для TVP-BVAR, что, конечно, хотелось бы реализовать.

Для ARIMA, экспоненциального сглаживания и тета-метода используется полностью автоматический выбор спецификации. Модели корректно сравниваются по прогнозной силе вне обучающей выборки. Сравнивая результаты двух подходов, многомерного байесовского и одномерного классического Анна приходит к смешанным результатам. Примерно в половине случаев лидирует байесовский векторный подход.

Анна хорошо разобралась в рассматриваемых моделях и успешно реализовала сравнение алгоритмов в среде R. 

Работа Анны заслуживает отличной оценки. 
