---
type: "Рецензия"
student: "Денисенко Анна Андреевна"
reviewer: "Демешев Борис Борисович"
supervisor: "Сонин Кирилл Исаакович"
topic: "Путь к демократии: эмиграция, подчинение и протест"
date: "21 мая 2017"
output: 
  pdf_document:
    keep_tex: true
    fig_caption: yes
    latex_engine: xelatex
    template: review_template.tex
geometry: "paper=a4paper, top=20.0mm,  bottom=20.0mm, left=20.0mm, right=20.0mm, includefoot"
lang: ru-RU  
---

В своей работе Анна описывает теоретическую игровую модель взаимодействия трёх игроков: правителя, советника и населения. Описав модель формально, Анна аккуратно изучает свойства модели и находит равновесия. 

Несомненным плюсом работы является то, что Анна находит решение модели аналитически. При этом Анна демонстрирует уверенное владение игровыми концепциями. Все переходы между формулами я не проверял, но там, где проверил, никаких ошибок не нашёл. Аналитическое решение модели на более чем 20 страницах занимает основную часть работы.

Рисунок 2 приведён без ссылок на оригинал, да и вызывает естественный вопрос: почему все режимы не скатываются в анократию? Судя по рисунку: в автократии положительных изменений больше, чем отрицательных, а в демократии — наоборот, положительных нет, а отрицательные есть. При этом во введении Анна пишет, что анократия — «хрупкое равновесие», хотя такая динамика — скорее признак устойчивого равновесия. 

В описании модели лучше было сразу добавить дерево. Без дерева игры воспринимать две с лишним страницы тексто тяжело. Пусть общее дерево игры со всеми стратегиями и было бы громоздким, с ним изложение было бы яснее. Анна же строит деревья только в процессе решения и только кусками. 

Существенным недостатком работы является только теоретическое рассмотрение вопроса. Введение содержит примеры реальных политических конфликтов. Какое отношение имеют эти примеры к рассматриваемому дереву игры, не понятно. Анна не делает попыток калибровки модели: предпосылки модели не сопоставляются с реальными конфликтами. Нет и попыток что-либо спрогнозировать с помощью этой модели. Поэтому мне очень понравилось, что советник иногда называется визирем. Правителя нужно было назвать султаном и ввести в игру Шахерезаду. Это модель-сказка :)

Работа очень красиво оформлена. Разве что после точек при сокращении имён в техе правильнее ставить неразрывный пробел тильдой. Пожалуй, это наиболее приятно оформленная работа из десятка ВКР прочитанных мной в этом году. 

Работа Анны заслуживает отличной оценки. 
