---
type: "Рецензия"
student: "Шипицына Марина Юрьевна"
reviewer: "Демешев Борис Борисович"
supervisor: "Малаховская Оксана Анатольевна"
topic: "Прогнозирование макроэкономических переменных с помощью методов частотной и байесовской эконометрики"
date: "21 мая 2017"
output: 
  pdf_document:
    keep_tex: true
    fig_caption: yes
    latex_engine: xelatex
    template: review_template.tex
geometry: "paper=a4paper, top=20.0mm,  bottom=20.0mm, left=20.0mm, right=20.0mm, includefoot"
lang: ru-RU  
---

В своей работе Марина сравнивает прогнозную силу BVAR модели с сопряжённым нормальным-обратным Уишарта априорным распределением. Модели сравниваются по прогнозной силе вне скользящей обучающей выборке. Марина изучает различные варианты выбора априорных гиперпараметров. Для автоматического подбора гиперпараметра используется максимизация маргинального правдподобия. В работе показано, что однозначного лидера среди рассматриваемых моделей нет.

Обзор литературы несколько затянут и занимает больше половины работы.

В работе много небрежностей. Марина пишет, что сезонно корректирует несколько рядов, в том числе и «ввод в действие новых жилых домов», однако данный ряд не упомянут в таблице всех рядов. Ковариационная матрица ошибок обозначается то $\Sigma$, то $\sigma^2$. Матрица констант — то $\Phi_c$, то $\Phi_{const}$. Есть немного странное заявление о сходимости алгоритма Гиббса с экспоненциальной скоростью. Если алгоритм так быстро сходится, то зачем делать 10000 итераций? Как выбираются гиперпараметры априорного распределения Миннесоты?

<!--
Неясно изложен выбор оптимального параметра $\theta$ жёсткости распределения. Если я правильно понял, то Марина пишет, что оптимум равен $0.5$ для каждого момента времени, при одном лаге в модели. А дальше Марина выбирает оптимальное количество лагов. И возможно, что для нового количества лагов оптимальным будет уже другое $\theta$. 
-->

Марина не указывает, чей код она использует для оценки моделей. Является ли код своей собственной разработкой или уже используется готовый? Учитывая сложность моделей, я предполагаю, что Марина использует готовый код. В этом нет ничего плохо, но обязательно нужно указывать, чей код используется. При этом код для организации скользящей выборки и систематического сравнения прогнозной силы всех моделей, по всей видимости, Марина писала сама. Вероятно, использовался R, matlab или julia. 

«Кому нужны книжки без картинок... - или хоть стишков, не понимаю!», говорила Алиса в Стране чудес. Это замечание в полной мере относится к работе Марины. В работе ноль (0) графиков. Можно было оформить сравнение моделей графически. Можно было показать, насколько сильно отличается логарифм маргинальной функции плотности для рассматриваемой сетки параметров. Можно было хотя бы изобразить рассматриваемые ряды до и после сезонной коррективки, чтобы проверить, насколько хорошо она сработала.

Очень неудобно оформлены таблицы. Все таблицы вынесены в конец работы и потому приходится листать работу туда-обратно. Страницы работы незанумерованы, поэтому возвращаться обратно сложнее. Подписей рядом с таблицей, объясняющих цифры в таблице, нет. В тексте работы содержимое таблицы объясняется, но идеальный график и идеальная таблица должны быть понятны, даже будучи полностью вырезанными из работы.

Работа Марины заслуживает хорошей или отличной оценки. 
