---
type: "Отзыв"
student: "Стерхов Сергей Игоревич"
reviewer: "Демешев Борис Борисович"
supervisor: "Демешев Борис Борисович"
topic: "Построение модели прогноза LTV для условно бесплатного игрового проекта"
date: "05 июня 2017"
output: 
  pdf_document:
    keep_tex: true
    fig_caption: yes
    latex_engine: xelatex
    template: review_template.tex
geometry: "paper=a4paper, top=20.0mm,  bottom=20.0mm, left=20.0mm, right=20.0mm, includefoot"
lang: ru-RU  
---

Работа Сергея посвящена решению практической задачи. Основная задача — спрогнозировать величину LTV, сколько денег потратят пользователи в игровом онлайн проекте. Работа построена на искусствено зашумленных реальных данных. 

В работе совсем нет графиков, хотя именно с этой задачи началось наше обсуждение работы осенью. Это существенный минус. 

Вторым существенным недостатком работы является обилие нереализованных идей. Об этих идеях упоминает и сам Сергей. Можно было: отдельно моделировать поведение игроков, тратящих крупные суммы в игре; исследовать модель, прогнозирующую расходы не отдельных игроков, а кластеров; учитывать признаки, связанные с поведением игрока в игре; сравнить прогнозную силу исследуемого алгоритма с другими стандартными алгоритмами прогнозирования LTV и так далее.

В работе есть и мелкие небрежности. Многие числа приводится с излишним количеством знаков после запятой. Сначала концепция LTV излагается в непрерывном времени, а затем происходит резкий переход в дискретное время без комментариев. 

Работа содержит небольшой но вполне релевантный обзор литературы о моделировании LTV. 

Большим плюсом ВКР является то, что Сергей решает реальную бизнес-задачу. Много времени в таких задачах уходит на чистку данных. Сергей подробно описывает, как проводится чистка данных.

Трудно оценивать работу студента не родного факультета, так как не с чем сравнить. Если бы ВКР Сергея защищалась на факультете экономики, то в зависимости от комиссии и презентации  получила бы от удовлетворительно до хорошо.


