---
type: "Рецензия"
student: "Абрамов Владислав Викторович"
reviewer: "Демешев Борис Борисович"
supervisor: "Малаховская Оксана Анатольевна"
topic: "Расчет фискального мультипликатора для российской экономики в рамках VAR-модели со знаковыми ограничениями"
date: "21 мая 2017"
output: 
  pdf_document:
    keep_tex: true
    fig_caption: yes
    latex_engine: xelatex
    template: review_template.tex
geometry: "paper=a4paper, top=20.0mm,  bottom=20.0mm, left=20.0mm, right=20.0mm, includefoot"
lang: ru-RU  
---

Работа Владислава посвящена оценке влияния шоков государственного потребления и государственных расходов на выпуск по российским данным. Я скептически отношусь к осмысленности оценки влияния ненаблюдаемых величин на наблюдаемые с помощью функций импульсного отклика и дальнейшей их интерпретации. Однако здесь Владислав следует довольно популярной в литературе методологии.

Работа оставляет при прочтении ощущение вопиющей небрежности.
<!--
Вызывает недоумение английский вопрос в русском тексте «Does the fiscal policy matter?» Если это цитирование английского текста, то где ссылка? Кстати, статья Блайндера называлась «Does fiscal policy matter?»
-->

В списке литературы дважды указана работа Friedman, Benjamin M. (1978), Crowding Out Or Crowding In? Также дважды в списке литературы указана работа Buiter, (1977), "Crowding out’ and the effectiveness of fiscal policy". Причём один раз работа Buiter указана с неверным годом (1973) и на эту неверную дату есть ссылка в тексте на странице 7. На странице 10 Владислав цитирует "Canova and Pappa (2003, 2008)", а в списке литературы есть только Canova and Pappa (2006). На странице 10 Владислав цитирует Canova, Pina (2005), а в списке литературы есть только Canova, Pina (1998). На странице 27 работа Mountford, Uhlig (2009) цитируется три раза, два из которых с опечатками. По тексту работы Владислава есть Ilzetzki (2009), (2011) и (2013), а в списке литературы — только Ilzetzki (2013). И так далее.

<!--
На странице 7 Владислав цитирует своими словами книгу Snowdon и Vane «Modern Macroeconomics: Its Origins, Development and Current State». Владислав указывает, что цитирует страницу 213, и это хорошо. Но ровно ту же цитату с той же ссылкой на стр. 213 можно найти в книге Пьера Лёмьё (Pierre Lemieux, Somebody in Charge: A solution to Recessions, стр. 60). Хотелось бы, чтобы это было случайное совпадение.
-->

Бездоказательно Владислав высказывает утверждение о бесполезности панельных VAR (страница 13). На мой взгляд, именно учет информации о похожих странах может помочь улучшить прогнозы VAR для отдельной страны. Двумя страницами позже разгрома панельных VAR Владислав называет работу по панельным VAR «знаковой», и пишет, что «эмпирические свидетельства подтверждаются теоретическими аргументами».  

Надеюсь, что фраза «**по мнению авторов**», написанная Владиславом на странице 19 о своей работе, является простой опиской.

Инфляция в таблице 1 явно измеряется в долях, а Владислав утверждает, что в процентах. Владислав крайне скупо описывает, что де-факто было сделано с данными. По каким критериям были отобраны 8 переменных? 

Как конкретно удалялась сезонность? «Для нивелирования сезонности... мы предположили, что ряды носят мультипликативный характер» — это не годится для описания метода. Более того, Владислав пишет, что брал **квартальные данные**. Однако график частных корреляций государственных доходов на странице 45 однозначно указывает на **месячные данные**. График PACF даёт высокие по модулю значения на 1, 12 и 13 лагах. Это объяснимо только для месячных данных, где текущий месяц зависит от прошлого месяца и от аналогичного месяца прошлого года. На мысль об использовании **месячных данных** наталкивает и график на странице 39. На графике государственных доходов легко видна годовая цикличность. А если перевести взгляд на график выше, то видно что в один цикл (один год) явно умещается больше четырёх изломов верхнего графика. С другой стороны, количество изломов на графиках на странице 40 указывает на **квартальные данные**. Возможно, что ряд по государственным доходам взят месячный? 

Как конкретно производилась идентификация, из работы тоже не очень ясно. Алгоритм на странице 24 — это плохой перевод не самого лучшего изложения алгоритма из документации пакета `VARsignR`. Здесь уместно сказать и слова в защиту Владислава. Владислав использует очень сложный алгоритм, существенно выходящий за рамки бакалаврской и даже магистерской программы. У меня создалось ощущение, что, с одной стороны, понимание алгоритма у Владислава поверхностное, а с другой стороны, что во всей ВШЭ найдётся не больше пяти человек, понимающих алгоритм лучше Владислава.

При написании ВКР Владислав использовал готовый пакет `VARsignR` для статистической среды R. Также в R построены требуемые графики. 

С учётом сложности алгоритма идентификации шоков работа Владислава заслуживает удовлетворительной оценки. 
