---
type: "Отзыв"
student: "Федотова Мирослава Андреевна"
reviewer: "Демешев Борис Борисович"
supervisor: "Демешев Борис Борисович"
topic: "Выявление индивидуальных предпочтений с помощью байесовской иерархической мультиномиальной логит-модели"
date: "15 мая 2017"
output: 
  pdf_document:
    keep_tex: true
    fig_caption: yes
    latex_engine: xelatex
    template: review_template.tex
geometry: "paper=a4paper, top=20.0mm,  bottom=20.0mm, left=20.0mm, right=20.0mm, includefoot"
lang: ru-RU  
---

Работа Мирославы посвящена анализу предпочтений индивидов. Мирослава анализирует данные реального эксперимента, в котором индивидам предлагается выбор из нескольких альтернативных пакетов мобильной связи.  

В своей работе Мирослава:

1. Успешно формулирует и оценивает иерархическую байесовскую мультиномиальную модель с разным количеством кластеров.

2. Проверяет устойчивость выводов к изменениям априорного распределения.

3. Определяет оптимальное число кластеров абонентов для получения наилучших прогнозов. 

Мирослава находит, что оптимальное число кластеров достаточно велико, доказывая тем самым преимущество байесовского подхода в данном конкретном случае. Оценить модель с различными коэффициентами в каждом из сотни кластеров в рамках классического максимального правдоподобия было бы невозможно. 

Достоинство модели со множеством кластеров состоит не только в более точных прогнозах по сравнению с агрегированной моделью, но и в более точном определении предпочтений каждого отдельного индивида. 

Было бы очень здорово реализовать автоматическое определение количества кластеров с помощью байесовского подхода. К сожалению, на это не хватило времени. 


Мирослава отлично разобралась байесовском подходе к оцениванию моделей, сформулировала требуемую модель на языке STAN и визуализировала результаты в среде R. Кроме иерархических мультиномиальных логит-моделей, Мирослава использовала нелинейный алгоритм t-SNE для снижения размерности и кластеризации абонентов.

Работа Мирославы заслуживает отличной оценки. 
