---
type: "Рецензия"
student: "Гимадиев Азат Фарсилович"
reviewer: "Демешев Борис Борисович"
supervisor: "Демешев Борис Борисович"
topic: "Прогнозирование стоимости опционов с помощью моделей краткосрочных процентных ставок"
date: "16 июня 2017"
output: 
  pdf_document:
    keep_tex: true
    fig_caption: yes
    latex_engine: xelatex
    template: review_template.tex
geometry: "paper=a4paper, top=20.0mm,  bottom=20.0mm, left=20.0mm, right=20.0mm, includefoot"
lang: ru-RU  
---

Работа Азата посвящена прогнозированию цены опционов. В названии заявлено использование моделей краткосрочных процентных ставок, но до этих моделей, к сожалению, в работе дело не доходит. Азат прогнозирует цену опциона в рамках наивных предположений о динамике цены акции.

Плюсы работы. С одной стороны Азат разобрался в базовых теоретических моделях оценивания опционов. Несмотря на некоторые мелкие неточности в описании модели, в целом видно, что Азат разобрался с моделью Блэка-Шоулса. С другой стороны, Азат работает с реальными данными и демонстрирует умение обработать сырые данные и реализовать алгоритм прогнозирования на языке python. 

Минусы работы. Работа состоит из отдельных кусков: блок теории и почти не связанный практический блок с прогнозами для четырех опционов на разные акции. Изложение трудно назвать аккуратным, но грубых ошибок нет. Также остались нереализованными прогнозы с моделированием динамики процентных ставок. 

Трудно оценивать работу студента другого факультета, поскольку нет возможности выбрать точку отсчёта. По меркам факультета экономики работа Азата заслуживает удовлетворительную или хорошую оценку.
